Repository ManageIQ/manageiq-providers-azure, pull requests merged in 2018-05, with the labels that each got.

#250 Exclude refresher files from AccessorMethodName warnings
  .rubocop_local.yml
Labels: cleanup, fine/no, gaprindashvili/no

#249 Rubocop cleanup
  app/models/manageiq/providers/azure/cloud_manager.rb
  app/models/manageiq/providers/azure/cloud_manager/metrics_capture.rb
  app/models/manageiq/providers/azure/cloud_manager/orchestration_stack.rb
  app/models/manageiq/providers/azure/cloud_manager/provision/configuration.rb
  app/models/manageiq/providers/azure/cloud_manager/provision_workflow.rb
  app/models/manageiq/providers/azure/cloud_manager/refresh_parser.rb
  app/models/manageiq/providers/azure/cloud_manager/vm_or_template_shared/scanning.rb
  app/models/manageiq/providers/azure/manager_mixin.rb
  app/models/manageiq/providers/azure/network_manager/refresh_parser.rb
  app/models/manageiq/providers/azure/regions.rb
Labels: cleanup, fine/no, gaprindashvili/no

#251 [GAPRINDASHVILI] [Changelog] Update for gaprindashvili-3 release
  CHANGELOG.md
Labels: documentation

#256 Test Vm reconnect while having more archived duplicates
  spec/models/manageiq/providers/azure/cloud_manager/targeted_refresher_spec.rb
Labels: test

#255 Archive VM with no status
  app/models/manageiq/providers/azure/inventory/parser/cloud_manager.rb
Labels: bug, gaprindashvili/yes

#260 Added French and Australian regions, fix Southeast Asia description.
  app/models/manageiq/providers/azure/regions.rb
  spec/models/manageiq/providers/azure/regions_spec.rb
Labels: fine/no, gaprindashvili/no
