Repository ManageIQ/manageiq-providers-azure, pull requests merged in 2018-02, with the labels that each got.

#207 Allowed cloud network without a zone should return everything
  spec/models/manageiq/providers/azure/cloud_manager/provision_workflow_spec.rb
Labels: test

#206 Treat securestring case insentive
  app/models/manageiq/providers/azure/cloud_manager/orchestration_template.rb
  spec/fixtures/orchestration_templates/azure_parameters.json
  spec/models/manageiq/providers/azure/cloud_manager/orchestration_template_spec.rb
Labels: bug, gaprindashvili/yes

#209 Handle possible race conditions for disks, events
  app/models/manageiq/providers/azure/cloud_manager/metrics_capture.rb
  app/models/manageiq/providers/azure/cloud_manager/refresh_parser.rb
Labels: bug, gaprindashvili/yes

#208 [Changelog] Update for Sprint 79
  CHANGELOG.md
Labels: documentation

#198 Added azure_tenant_id to API_ALLOWED_ATTRIBUTES
  app/models/manageiq/providers/azure/cloud_manager.rb
Labels: enhancement

#211 Update azure-armrest to 0.9.6
  manageiq-providers-azure.gemspec
Labels: fine/yes, gaprindashvili/yes
