Repository ManageIQ/manageiq-providers-azure, pull requests merged in 2018-11, with the labels that each got.

#300 Handle possibility that disk might not have sku
  app/models/manageiq/providers/azure/cloud_manager/refresh_parser.rb
  app/models/manageiq/providers/azure/inventory/parser/cloud_manager.rb
  spec/models/manageiq/providers/azure/cloud_manager/azure_refresher_spec_common.rb
Labels: bug, fine/yes, gaprindashvili/yes, hammer/yes

#299 [HAMMER] Add translations for hammer
  locale/es/ManageIQ_Providers_Azure.po
  locale/fr/ManageIQ_Providers_Azure.po
  locale/ja/ManageIQ_Providers_Azure.po
  locale/pt_BR/ManageIQ_Providers_Azure.po
  locale/zh_CN/ManageIQ_Providers_Azure.po
Labels: internationalization

#303 [Changelog] Update for Sprint 98 and H-B1
  CHANGELOG.md
Labels: documentation

#302 Handle regions where metrics are unsupported
  app/models/manageiq/providers/azure/cloud_manager/metrics_capture.rb
  spec/models/manageiq/providers/azure/cloud_manager/metrics_capture_spec.rb
Labels: blocker, bug, fine/yes, gaprindashvili/yes, hammer/yes

#307 Always set vm_or_template.connection_state
  app/models/manageiq/providers/azure/cloud_manager/refresh_parser.rb
  app/models/manageiq/providers/azure/cloud_manager/vm.rb
  app/models/manageiq/providers/azure/inventory/parser/cloud_manager.rb
  spec/models/manageiq/providers/azure/cloud_manager/azure_refresher_spec_common.rb
Labels: refactoring

#306 Service dialog for orchestration template no longer contains tenant selection
  spec/models/manageiq/providers/azure/cloud_manager/orchestration_template_spec.rb
Labels: blocker, gaprindashvili/yes, hammer/yes

#308 [Changelog] Update for Sprint 99
  CHANGELOG.md
Labels: documentation

#309 [HAMMER] [Changelog] Update for Hammer RC2
  CHANGELOG.md
Labels: documentation
