Repository ManageIQ/manageiq-providers-azure, pull requests merged in 2018-04, with the labels that each got.

#233 Ignore deployment events
  app/models/manageiq/providers/azure/cloud_manager.rb
  config/settings.yml
  spec/models/manageiq/providers/azure/cloud_manager_spec.rb
Labels: bug, gaprindashvili/yes, performance

#232 [Changelog] Update for Sprint 82
  CHANGELOG.md
Labels: documentation

#235 Change saver_strategy value to String
  app/models/manageiq/providers/azure/inventory_collection_default/cloud_manager.rb
  config/settings.yml
  spec/models/manageiq/providers/azure/cloud_manager/azure_refresher_spec_common.rb
  spec/models/manageiq/providers/azure/cloud_manager/deployments_caching_spec.rb
Labels: technical debt

#234 Fix specs for targeted api collection threshold
  app/models/manageiq/providers/azure/inventory/collector/target_collection.rb
  spec/models/manageiq/providers/azure/cloud_manager/azure_refresher_spec_common.rb
  spec/models/manageiq/providers/azure/cloud_manager/targeted_refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_0/cloud_network_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_0/lb_created_by_stack_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_0/lb_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_0/lb_vms_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_0/lb_with_vms_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_0/lbs_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_0/multiple_targets_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_0/network_port_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_0/orchestration_stack_lb_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_0/orchestration_stack_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_0/orchestration_stack_vm_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_0/powered_off_vm_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_0/powered_on_vm_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_0/resource_group_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_0/security_group_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_0/template_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_0/vm_with_managed_disk_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_500/cloud_network_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_500/lb_created_by_stack_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_500/lb_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_500/lb_vms_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_500/lb_with_vms_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_500/lbs_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_500/multiple_targets_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_500/network_port_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_500/orchestration_stack_lb_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_500/orchestration_stack_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_500/orchestration_stack_vm_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_500/powered_off_vm_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_500/powered_on_vm_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_500/resource_group_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_500/security_group_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_500/template_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_500/vm_with_managed_disk_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted_scope/resource_group_refresh.yml
Labels: gaprindashvili/yes, test

#241 Update azure-armrest gem to 0.9.10
  manageiq-providers-azure.gemspec
Labels: blocker, fine/yes, gaprindashvili/yes

#231 Azure labels and tags support for old refresh mech
  app/models/manageiq/providers/azure/cloud_manager/refresh_parser.rb
  spec/models/manageiq/providers/azure/cloud_manager/azure_refresher_spec_common.rb
  spec/models/manageiq/providers/azure/cloud_manager/refresher_spec.rb
Labels: blocker, fine/no

#229 Azure labels and tag mapping support for a new refresh
  app/models/manageiq/providers/azure/inventory/parser/cloud_manager.rb
  app/models/manageiq/providers/azure/inventory/persister.rb
  app/models/manageiq/providers/azure/inventory/persister/cloud_manager.rb
  app/models/manageiq/providers/azure/inventory/persister/target_collection.rb
  app/models/manageiq/providers/azure/inventory_collection_default/cloud_manager.rb
  spec/models/manageiq/providers/azure/cloud_manager/azure_refresher_spec_common.rb
  spec/models/manageiq/providers/azure/cloud_manager/compare_legacy_and_new_refresh_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager/deployments_caching_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager/refresher_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager/targeted_refresher_scope_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager/targeted_refresher_spec.rb
Labels: blocker, fine/no, gaprindashvili/yes

#242 [FINE] labels and tags mapping support
  app/models/manageiq/providers/azure/cloud_manager/refresh_parser.rb
  spec/models/manageiq/providers/azure/cloud_manager/refresher_spec.rb
Labels: enhancement

#246 [Changelog] Update for Sprint 84
  CHANGELOG.md
Labels: documentation

#236 Convert api-version strings to actual strings
  app/models/manageiq/providers/azure/manager_mixin.rb
  app/models/manageiq/providers/azure/refresh_helper_methods.rb
  config/settings.yml
Labels: refactoring
