Repository ManageIQ/manageiq-providers-azure, pull requests merged in 2018-06, with the labels that each got.

#262 [Changelog] Update for Gaprindashvili-3 release
  CHANGELOG.md
Labels: documentation

#254 Persister: InventoryCollection building through add_collection()
  app/models/manageiq/providers/azure/inventory/persister.rb
  app/models/manageiq/providers/azure/inventory/persister/cloud_manager.rb
  app/models/manageiq/providers/azure/inventory/persister/definitions/cloud_collections.rb
  app/models/manageiq/providers/azure/inventory/persister/definitions/network_collections.rb
  app/models/manageiq/providers/azure/inventory/persister/network_manager.rb
  app/models/manageiq/providers/azure/inventory/persister/target_collection.rb
Labels: refactoring

#264 Fix root disk size, swap disk size
  app/models/manageiq/providers/azure/cloud_manager/refresh_parser.rb
  app/models/manageiq/providers/azure/inventory/parser/cloud_manager.rb
  spec/models/manageiq/providers/azure/cloud_manager/azure_refresher_spec_common.rb
Labels: bug, fine/yes, gaprindashvili/yes

#265 Add display name for flavor
  app/models/manageiq/providers/azure/cloud_manager/flavor.rb
Labels: enhancement

#269 [Changelog] Update for Sprint 88
  CHANGELOG.md
Labels: documentation
