Repository ManageIQ/manageiq-providers-azure, pull requests merged in 2018-07, with the labels that each got.

#271 Persister: optimized InventoryCollection definitions
  app/models/manageiq/providers/azure/inventory/persister/definitions/cloud_collections.rb
  app/models/manageiq/providers/azure/inventory/persister/definitions/network_collections.rb
  app/models/manageiq/providers/azure/inventory/persister/network_manager.rb
  app/models/manageiq/providers/azure/inventory_collection_default/cloud_manager.rb
  app/models/manageiq/providers/azure/inventory_collection_default/network_manager.rb
Labels: enhancement

#272 Update series name to work with Azure stack
  app/models/manageiq/providers/azure/cloud_manager/refresh_parser.rb
  app/models/manageiq/providers/azure/inventory/collector/target_collection.rb
  app/models/manageiq/providers/azure/inventory/parser/cloud_manager.rb
  spec/models/manageiq/providers/azure/cloud_manager/azure_refresher_spec_common.rb
Labels: enhancement

#267 Set parent for VM's where possible
  app/models/manageiq/providers/azure/cloud_manager/refresh_parser.rb
  app/models/manageiq/providers/azure/inventory/parser/cloud_manager.rb
  app/models/manageiq/providers/azure/refresh_helper_methods.rb
  spec/models/manageiq/providers/azure/cloud_manager/azure_refresher_spec_common.rb
  spec/models/manageiq/providers/azure/cloud_manager/refresher_spec.rb
Labels: fine/no, gaprindashvili/yes, refactoring

#279 [Changelog] Update for Sprint 90
  CHANGELOG.md
Labels: documentation

#280 Enable graph refresh by default
  config/settings.yml
Labels: enhancement

#281 InventoryCollection builder_params -> default_values
  app/models/manageiq/providers/azure/inventory/persister/definitions/network_collections.rb
Labels: cleanup

#282 [Changelog] Update for Sprint 91
  CHANGELOG.md
Labels: documentation
