Repository ManageIQ/manageiq-providers-azure, pull requests merged in 2018-09, with the labels that each got.

#286 Inventory::Builder functions moved to Inventory
  app/models/manageiq/providers/azure/builder.rb
  app/models/manageiq/providers/azure/inventory.rb
Labels: refactoring

#288 Update azure-armrest gem to 0.9.13
  manageiq-providers-azure.gemspec
Labels: fine/yes, gaprindashvili/yes

#290 [Changelog] Update for Sprint 94
  CHANGELOG.md
Labels: documentation

#289 Add running of common core provider specs
  lib/tasks_private/spec.rake
Labels: test

#293 [HAMMER] [Changelog] Update for Hammer Beta-1 release
  CHANGELOG.md
Labels: documentation
