Repository ManageIQ/manageiq-providers-azure, pull requests merged in 2018-03, with the labels that each got.

#216 Consolidate Azure refresh workers
  app/models/manageiq/providers/azure/cloud_manager/refresh_worker.rb
  app/models/manageiq/providers/azure/cloud_manager/refresher.rb
  spec/models/manageiq/providers/azure/cloud_manager/refresh_worker_spec.rb
Labels: bug, gaprindashvili/yes

#214 [Changelog] Update for Sprint 80
  CHANGELOG.md
Labels: documentation

#215 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-2
  CHANGELOG.md
Labels: documentation

#217 Azure graph refresh targeted
  app/models/manageiq/providers/azure/inventory/collector.rb
  app/models/manageiq/providers/azure/inventory/collector/cloud_manager.rb
  app/models/manageiq/providers/azure/inventory/collector/target_collection.rb
  app/models/manageiq/providers/azure/inventory/parser/cloud_manager.rb
  app/models/manageiq/providers/azure/inventory/parser/network_manager.rb
  app/models/manageiq/providers/azure/inventory/persister.rb
  app/models/manageiq/providers/azure/inventory/persister/target_collection.rb
  app/models/manageiq/providers/azure/inventory_collection_default/network_manager.rb
  spec/models/manageiq/providers/azure/cloud_manager/azure_refresher_spec_common.rb
  spec/models/manageiq/providers/azure/cloud_manager/compare_legacy_and_new_refresh_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager/refresher_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager/targeted_refresher_scope_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager/targeted_refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/lb_created_by_stack_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/lb_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/lb_vms_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/lb_with_vms_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/lbs_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/orchestration_stack_lb_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/orchestration_stack_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/orchestration_stack_vm_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/powered_off_vm_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/powered_on_vm_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/template_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/vm_with_managed_disk_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted_scope/lb_created_by_stack_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted_scope/lb_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted_scope/lb_vms_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted_scope/lb_with_vms_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted_scope/lbs_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted_scope/orchestration_stack_lb_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted_scope/orchestration_stack_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted_scope/orchestration_stack_vm_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted_scope/powered_off_vm_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted_scope/powered_on_vm_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted_scope/template_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted_scope/vm_with_managed_disk_refresh.yml
Labels: enhancement

#222 Azure events targeted
  app/models/manageiq/providers/azure/cloud_manager/event_target_parser.rb
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/availabilitySets_delete_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/availabilitySets_write_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/deployments_exportTemplate_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/deployments_validate_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/disks_delete_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/disks_write_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/images_delete_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/images_write_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/loadBalancers_delete_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/loadBalancers_write_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/locks_delete_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/locks_write_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/networkInterfaces_delete_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/networkInterfaces_write_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/networkSecurityGroups_delete_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/networkSecurityGroups_securityRules_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/networkSecurityGroups_write_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/publicIPAddresses_delete_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/publicIPAddresses_write_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/publicIpAddresses_delete_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/publicIpAddresses_write_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/snapshots_delete_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/snapshots_write_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/storageAccounts_delete_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/storageAccounts_write_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/subscriptions_resourceGroups_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/subscriptions_resourcegroups_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/virtualMachines_deallocate_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/virtualMachines_delete_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/virtualMachines_generalize_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/virtualMachines_powerOff_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/virtualMachines_restart_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/virtualMachines_start_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/virtualMachines_write_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/virtualNetworks_delete_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/virtualNetworks_subnets_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/virtualNetworks_write_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/virtualnetworks_delete_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/virtualnetworks_subnets_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/virtualnetworks_write_EndRequest.json
  spec/models/manageiq/providers/azure/cloud_manager/event_target_parser_spec.rb
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/event_target_parser/deployments_write_EndRequest.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/event_target_parser/loadBalancers_write_EndRequest.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/event_target_parser/networkInterfaces_delete_EndRequest.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/event_target_parser/networkInterfaces_write_EndRequest.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/event_target_parser/networkSecurityGroups_write_EndRequest.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/event_target_parser/publicIPAddresses_write_EndRequest.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/event_target_parser/virtualMachines_deallocate_EndRequest.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/event_target_parser/virtualMachines_delete_EndRequest.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/event_target_parser/virtualMachines_restart_EndRequest.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/event_target_parser/virtualMachines_start_EndRequest.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/event_target_parser/virtualMachines_write_EndRequest.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/event_target_parser/virtualNetworks_write_EndRequest.yml
Labels: refactoring, test

#226 Fix event JSONs on case-insensitive filesystems
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/publicIpAddresses_delete_EndRequest_downcase.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/publicIpAddresses_write_EndRequest_downcase.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/subscriptions_resourcegroups_EndRequest_downcase.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/virtualnetworks_delete_EndRequest_downcase.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/virtualnetworks_subnets_EndRequest_downcase.json
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/event_data/virtualnetworks_write_EndRequest_downcase.json
  spec/models/manageiq/providers/azure/cloud_manager/event_target_parser_spec.rb
Labels: bug, test

#225 Fix case-sensitive events ems_ref parsing
  app/models/manageiq/providers/azure/cloud_manager/event_target_parser.rb
  spec/models/manageiq/providers/azure/cloud_manager/event_target_parser_spec.rb
Labels: bug, events

#228 Add a tasks to delete and regenerate all cassettes
  lib/tasks/azure.rake
Labels: developer, test

#223 [Changelog] Update for Sprint 81
  CHANGELOG.md
Labels: documentation

#224 Add router collection to refresh parser
  app/models/manageiq/providers/azure/inventory/collector.rb
  app/models/manageiq/providers/azure/inventory/collector/network_manager.rb
  app/models/manageiq/providers/azure/inventory/collector/target_collection.rb
  app/models/manageiq/providers/azure/inventory/parser/network_manager.rb
  app/models/manageiq/providers/azure/inventory/persister/network_manager.rb
  app/models/manageiq/providers/azure/inventory/persister/target_collection.rb
  app/models/manageiq/providers/azure/inventory_collection_default/network_manager.rb
  app/models/manageiq/providers/azure/network_manager/refresh_parser.rb
  app/models/manageiq/providers/azure/refresh_helper_methods.rb
  config/settings.yml
  lib/tasks/azure.rake
  spec/models/manageiq/providers/azure/cloud_manager/azure_refresher_spec_common.rb
  spec/models/manageiq/providers/azure/cloud_manager/deployments_caching_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager/refresher_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager/targeted_refresher_scope_spec.rb
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_inventory_object.yml
Labels: enhancement, gaprindashvili/yes
