Repository ManageIQ/manageiq-providers-azure, pull requests merged in 2018-12, with the labels that each got.

#311 Bump master travis.yml to ruby 2.3.8.
  .travis.yml
Labels: gaprindashvili/yes, hammer/yes, test

#312 Change FactoryGirl to FactoryBot
  spec/factories/ext_management_system.rb
  spec/factories/image.rb
  spec/factories/orchestration_template.rb
  spec/factories/resource_group.rb
  spec/models/manageiq/providers/azure/cloud_manager/azure_refresher_spec_common.rb
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/runner_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager/event_target_parser_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager/metrics_capture_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager/orchestration_stack_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager/orchestration_template_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager/provision/cloning_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager/provision/configuration_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager/provision_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager/provision_workflow_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager/refresh_worker_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager/targeted_refresher_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager/vm_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager_spec.rb
  spec/models/manageiq/providers/azure/refresh_helper_methods_spec.rb
Labels: dependencies, gaprindashvili/no, hammer/no

#313 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-7
  CHANGELOG.md
Labels: documentation

#316 Bump master travis.yml to ruby 2.4.5
  .travis.yml
Labels: test

#317 [HAMMER] Bump hammer travis.yml to ruby 2.4.5
  .travis.yml
Labels: test
