Repository ManageIQ/manageiq-providers-azure, pull requests merged in 2019-11, with the labels that each got.

#364 Add and subclass scan_timeout_adjustment_multiplier method
  app/models/manageiq/providers/azure/cloud_manager/vm_or_template_shared/scanning.rb
Labels: refactoring, smart state

#366 Add CODEOWNERS
  .github/CODEOWNERS
Labels: documentation

#367 Remove checking for ems_ref_obj => nil
  spec/models/manageiq/providers/azure/cloud_manager/azure_refresher_spec_common.rb
Labels: cleanup

#368 Rely on the default implementation of .ems_class
  app/models/manageiq/providers/azure/network_manager/event_catcher.rb
  app/models/manageiq/providers/azure/network_manager/metrics_collector_worker.rb
  app/models/manageiq/providers/azure/network_manager/refresh_worker.rb
Labels: refactoring

#371 Remove the require_nested call for removed refresh worker
  app/models/manageiq/providers/azure/network_manager.rb
Labels: bug
