Repository ManageIQ/manageiq-providers-azure, pull requests merged in 2019-08, with the labels that each got.

#339 Remove legacy refresh option and code
  app/models/manageiq/providers/azure/cloud_manager.rb
  app/models/manageiq/providers/azure/cloud_manager/refresh_parser.rb
  app/models/manageiq/providers/azure/cloud_manager/refresher.rb
  app/models/manageiq/providers/azure/network_manager.rb
  app/models/manageiq/providers/azure/network_manager/refresh_parser.rb
  app/models/manageiq/providers/azure/network_manager/refresher.rb
  config/settings.yml
  spec/models/manageiq/providers/azure/cloud_manager/azure_refresher_spec_common.rb
  spec/models/manageiq/providers/azure/cloud_manager/compare_legacy_and_new_refresh_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager/targeted_refresher_scope_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager/targeted_refresher_spec.rb
Labels: cleanup, ivanchuk/no

#342 [Changelog] Update for Ivanchuk Beta2
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#343 Set the vm_uid_ems in the event parser if it's a VM
  app/models/manageiq/providers/azure/cloud_manager/event_parser.rb
  spec/models/manageiq/providers/azure/cloud_manager/event_parser_spec.rb
Labels: bug, hammer/yes, ivanchuk/yes

#344 [Changelog] Update for Hammer-10
  CHANGELOG.md
Labels: documentation, hammer/yes

#345 Always return counters and counter_values
  app/models/manageiq/providers/azure/cloud_manager/metrics_capture.rb
  spec/models/manageiq/providers/azure/cloud_manager/metrics_capture_spec.rb
Labels: blocker, bug, ivanchuk/yes
