Repository ManageIQ/manageiq-providers-azure, pull requests merged in 2019-09, with the labels that each got.

#347 fix invalid and syntax
  app/models/manageiq/providers/azure/cloud_manager/metrics_capture.rb
Labels: blocker, bug, ivanchuk/yes

#349 [Changelog] Rollup of Ivanchuk releases
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#352 update_attributes has been deprecated
  app/models/manageiq/providers/azure/cloud_manager/vm/operations.rb
  app/models/manageiq/providers/azure/cloud_manager/vm/operations/power.rb
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/azure/cloud_manager_spec.rb
Labels: technical debt

#353 [Changelog] Update for Sprint 120
  CHANGELOG.md
Labels: documentation

#355 Parse the Azure Event Timestamp into a DateTime
  app/models/manageiq/providers/azure/cloud_manager/event_catcher/stream.rb
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher/stream_spec.rb
Labels: bug
