Repository ManageIQ/manageiq-providers-azure, pull requests merged in 2019-10, with the labels that each got.

#356 [Changelog] Update for Sprint 121
  CHANGELOG.md
Labels: documentation

#359 Remove zanata.xml
  zanata.xml
Labels: cleanup

#358 Remove zanata from README
  README.md
Labels: cleanup

#360 Test ruby 2.5.7/2.6.5, see: ManageIQ/manageiq#19414
  .travis.yml
Labels: test
