Repository ManageIQ/manageiq-providers-azure, pull requests merged in 2020-03, with the labels that each got.

#381 Fix shadowed exceptions in Scanning::Job
  app/models/manageiq/providers/azure/cloud_manager/scanning/job.rb
Labels: bug

#382 [IVANCHUK] Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#383 [JANSA] Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#384 remove inventory object refresh
  app/models/manageiq/providers/azure/cloud_manager.rb
  app/models/manageiq/providers/azure/network_manager.rb
  spec/models/manageiq/providers/azure/cloud_manager/azure_refresher_spec_common.rb
  spec/models/manageiq/providers/azure/cloud_manager/deployments_caching_spec.rb
Labels: cleanup

#386 Fix spec broken by removal of inventory obj refresh
  spec/models/manageiq/providers/azure/cloud_manager/azure_refresher_spec_common.rb
Labels: test

#387 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation
