Repository ManageIQ/manageiq-providers-azure, pull requests merged in 2020-06, with the labels that each got.

#399 Use vmId for uid_ems for instances
  app/models/manageiq/providers/azure/inventory/parser/cloud_manager.rb
  spec/models/manageiq/providers/azure/cloud_manager/azure_refresher_spec_common.rb
Labels: enhancement

#401 Move combined refresh workers to core
  app/models/manageiq/providers/azure/cloud_manager/refresh_worker.rb
Labels: refactoring

#402 Mark the event monitor running before first event
  app/models/manageiq/providers/azure/cloud_manager/event_catcher/runner.rb
Labels: bug, jansa/yes?
