Repository ManageIQ/manageiq-providers-azure, pull requests merged in 2020-05, with the labels that each got.

#392 Adjusted DDF schema and removed create/edit methods
  app/models/manageiq/providers/azure/manager_mixin.rb
Labels: enhancement

#393 Fix README to point to travis-ci.com instead of travis-ci.org
  README.md
Labels: bug, developer

#394 Removing deprecated Gemnasium badge
  README.md
Labels: developer

#391 Add a shell script for adding a user
  tools/add_user.sh
Labels: enhancement, tools

#395 Loosen azure-armrest dependency to 0.9
  manageiq-providers-azure.gemspec
Labels: dependencies

#397 Add supports terminate feature
  app/models/manageiq/providers/azure/cloud_manager/vm/operations.rb
  spec/models/manageiq/providers/azure/cloud_manager/vm_spec.rb
Labels: bug, jansa/yes?
