Repository ManageIQ/manageiq-providers-azure, pull requests merged in 2020-09, with the labels that each got.

#408 Fix bug where new regions are not reflected in the list
  app/models/manageiq/providers/azure/manager_mixin.rb
  spec/models/manageiq/providers/azure/cloud_manager_spec.rb
Labels: bug, jansa/yes?

#409 Prefer to not memoize at all for dynamic params
  app/models/manageiq/providers/azure/manager_mixin.rb
  spec/models/manageiq/providers/azure/cloud_manager_spec.rb
Labels: cleanup, jansa/yes?

#411 Use the tag_mapper from the core Persister
  app/models/manageiq/providers/azure/inventory/persister.rb
  app/models/manageiq/providers/azure/inventory/persister/cloud_manager.rb
  app/models/manageiq/providers/azure/inventory/persister/target_collection.rb
Labels: refactoring

#412 Make the default credentials required in the provider DDF
  app/models/manageiq/providers/azure/manager_mixin.rb
Labels: bug

#413 Prefer ManageIQ::Password over legacy MiqPassword constant
  app/models/manageiq/providers/azure/manager_mixin.rb
Labels: technical debt
