Repository ManageIQ/manageiq-providers-azure, pull requests merged in 2020-07, with the labels that each got.

#404 Filter out cloud networks with no cloud subnets during provisioning
  app/models/manageiq/providers/azure/cloud_manager/provision_workflow.rb
  spec/models/manageiq/providers/azure/cloud_manager/provision_workflow_spec.rb
Labels: bug

#406 Add APP_PATH to allow using Rails directly
  bin/rails
Labels: developer, enhancement

#405 Rename the key_pairs collection
  app/models/manageiq/providers/azure/inventory/persister/definitions/cloud_collections.rb
Labels: refactoring
