Repository ManageIQ/manageiq-providers-azure, pull requests merged in 2020-10, with the labels that each got.

#417 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: test

#416 Case sensitive support for label mapping
  app/models/manageiq/providers/azure/inventory/persister.rb
Labels: enhancement

#419 Fix .rubocop_local.yml
  .rubocop_local.yml
Labels: developer
