Repository ManageIQ/manageiq-providers-azure, pull requests merged in 2021-02, with the labels that each got.

#435 Convert `supports_#{op}?` to `supports?(op)`
  app/models/manageiq/providers/azure/cloud_manager/event_catcher.rb
  app/models/manageiq/providers/azure/cloud_manager/template.rb
  app/models/manageiq/providers/azure/cloud_manager/vm/operations.rb
  app/models/manageiq/providers/azure/cloud_manager/vm/operations/power.rb
  spec/models/manageiq/providers/azure/cloud_manager/event_catcher_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager/vm_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager_spec.rb
Labels: refactoring

#436 The Per Disk Read/Write Per Sec Metric was removed
  app/models/manageiq/providers/azure/cloud_manager/metrics_capture.rb
  spec/models/manageiq/providers/azure/cloud_manager/metrics_capture_spec.rb
Labels: bug, jansa/yes?, kasparov/yes?

#437 Adjust empty/initial values for select fields in DDF schemas
  app/models/manageiq/providers/azure/manager_mixin.rb
Labels: enhancement

#439 Persist the Microsoft.Insights capability to the EMS#capabilities column
  app/models/manageiq/providers/azure/cloud_manager.rb
  app/models/manageiq/providers/azure/manager_mixin.rb
Labels: bug, performance

#441 Replace ems.insights? stubs with setting capabilities
  spec/models/manageiq/providers/azure/cloud_manager/metrics_capture_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager_spec.rb
Labels: cleanup, test
