Repository ManageIQ/manageiq-providers-azure, pull requests merged in 2021-03, with the labels that each got.

#444 Don't manually set the templates model_class
  app/models/manageiq/providers/azure/inventory/persister/definitions/cloud_collections.rb
Labels: refactoring

#447 Test with ruby 2.6.6 and 2.7.2 per ManageIQ/manageiq#19678
  .travis.yml
Labels: test

#432 Add systemd unit files for workers
  build/systemd_units/manageiq-providers-azure_cloud_manager_event_catcher.target
  build/systemd_units/manageiq-providers-azure_cloud_manager_event_catcher@.service
  build/systemd_units/manageiq-providers-azure_cloud_manager_metrics_collector.target
  build/systemd_units/manageiq-providers-azure_cloud_manager_metrics_collector@.service
  build/systemd_units/manageiq-providers-azure_cloud_manager_refresh.target
  build/systemd_units/manageiq-providers-azure_cloud_manager_refresh@.service
Labels: technical debt
