Repository ManageIQ/manageiq-providers-azure, pull requests merged in 2022-05, with the labels that each got.

#502 Update apt-cache before running apt-get install
  bin/before_install
Labels: bug, test

#501 Add manual option for CI github workflow
  .github/workflows/ci.yaml
Labels: test

#503 Improve Invalid Credentials error message
  app/models/manageiq/providers/azure/manager_mixin.rb
Labels: bug, najdorf/yes?

#504 Create and delete cloud databases
  app/models/manageiq/providers/azure/cloud_manager/cloud_database.rb
  spec/factories/cloud_database.rb
  spec/models/manageiq/providers/azure/cloud_manager/cloud_database_spec.rb
Labels: enhancement

#507 Add connect service options
  app/models/manageiq/providers/azure/cloud_manager/cloud_database.rb
  app/models/manageiq/providers/azure/inventory/collector/target_collection.rb
  app/models/manageiq/providers/azure/manager_mixin.rb
  app/models/manageiq/providers/azure/refresh_helper_methods.rb
  spec/models/manageiq/providers/azure/cloud_manager/cloud_database_spec.rb
  spec/models/manageiq/providers/azure/cloud_manager_spec.rb
Labels: enhancement

#508 Remove refresh helper methods from manager mixin
  app/models/manageiq/providers/azure/manager_mixin.rb
Labels: refactoring
