Repository ManageIQ/manageiq-providers-azure, pull requests merged in 2022-10, with the labels that each got.

#520 Targeted refresh creates resources from other regions based on events
  app/models/manageiq/providers/azure/inventory/collector/target_collection.rb
  app/models/manageiq/providers/azure/refresh_helper_methods.rb
  spec/models/manageiq/providers/azure/cloud_manager/azure_refresher_spec_common.rb
  spec/models/manageiq/providers/azure/cloud_manager/targeted_refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_0/vm_in_other_region_refresh.yml
  spec/vcr_cassettes/manageiq/providers/azure/cloud_manager/refresher_targeted/targeted_api_collection_threshold_500/vm_in_other_region_refresh.yml
Labels: bug

#522 Remove useless gather_data_for_this_region method
  app/models/manageiq/providers/azure/inventory/collector.rb
  app/models/manageiq/providers/azure/inventory/collector/target_collection.rb
  app/models/manageiq/providers/azure/refresh_helper_methods.rb
  spec/models/manageiq/providers/azure/refresh_helper_methods_spec.rb
Labels: technical debt

#525 Add updated market_image_uris for newer versions
  config/settings.yml
Labels: enhancement

#524 Handle Forbidden errors fetching stack templates
  app/models/manageiq/providers/azure/inventory/collector.rb
  app/models/manageiq/providers/azure/inventory/parser/network_manager.rb
Labels: bug

#526 Collect filtered marked images by default
  config/settings.yml
  spec/models/manageiq/providers/azure/cloud_manager/azure_refresher_spec_common.rb
  spec/models/manageiq/providers/azure/cloud_manager/refresher_spec.rb
Labels: enhancement

#523 Fix network ports memoization and remove unused `RefreshHelperMethods` methods
  app/models/manageiq/providers/azure/inventory/collector.rb
  app/models/manageiq/providers/azure/inventory/collector/target_collection.rb
  app/models/manageiq/providers/azure/refresh_helper_methods.rb
Labels: technical debt

#527 Upgrade workflows to actions/checkout@v3
  .github/workflows/ci.yaml
Labels: enhancement, test
