Repository ManageIQ/manageiq-providers-azure, pull requests merged in 2022-02, with the labels that each got.

#490 Remove Hakiri
  README.md
Labels: cleanup, developer

#493 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .travis.yml
  README.md
  bin/before_install
  bin/ci/after_script
  bin/setup
  manageiq-providers-azure.gemspec
Labels: developer, test

#494 Add Build History Graph to README.md
  README.md
Labels: developer, test

#491 Skip instances if we cannot find the flavor
  app/models/manageiq/providers/azure/inventory/parser/cloud_manager.rb
Labels: bug, morphy/yes?

#492 Don't allow logical regions to be selected
  config/regions.yml
  lib/tasks_private/azure.rake
Labels: bug, morphy/yes?, najdorf/yes?

#495 Skip Azure regions with NULL physicalLocations
  config/regions.yml
  lib/tasks_private/azure.rake
Labels: bug

#496 Fix self.verify_credentials region nil
  app/models/manageiq/providers/azure/manager_mixin.rb
Labels: bug

#497 Run an API call when verifying credentials
  app/models/manageiq/providers/azure/manager_mixin.rb
Labels: bug

#498 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: developer, test
